version: '3'

services:
  razor_pages:
    image: razor_pages:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_razor_pages$
    volumes:
      - C:\git\Learning\ASP_Net Core Beginner\Razor_Pages\Razor_Pages:/app
      - C:\Users\cgfoo\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_razor_pages$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_razor_pages$ bin/Debug/netcoreapp2.0/Razor_Pages.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
